on:
  push

jobs:
  ssh-to-dreamhost:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: SSH to Dreamhost
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        command_timeout: 30m
        script: | 
          cd ~/liberatoryAIEcosystem && git pull origin main
